name: CD for Python Stock Quote

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t python-stock-quote .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag and Push Docker image
        run: |
          docker tag python-stock-quote cfwwong/python-stock-quote:latest
          docker push cfwwong/python-stock-quote:latest

  pull-image-and-run-container:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Latest Image & Restart Container on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Stop and remove existing container (if running)
            docker stop my-container || true
            docker rm my-container || true

            # Pull the latest image from Docker Hub
            docker pull cfwwong/python-stock-quote:latest

            # Run the container
            docker run -d --name my-container -p 80:5000 cfwwong/python-stock-quote:latest